version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/" # search in .github/workflows under root `/`
  schedule:
    interval: "weekly" # check for action update every week
